version: "3.8"

services:
  sharkord:
    image: ghcr.io/sharkord/sharkord:v0.0.20
    container_name: sharkord-dev
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    environment:
      - SHARKORD_WEBRTC_ANNOUNCED_ADDRESS=127.0.0.1
    volumes:
      - ./dist/sharkord-vid-with-friends:/home/bun/.config/sharkord/plugins/sharkord-vid-with-friends
    ports:
      - "3000:3000"
      - "10000-10100:10000-10100/udp"
