/**
 * /vid-bugreport <description> — Create an anonymized GitHub issue for bug reports.
 *
 * With githubToken set: posts a full issue via REST API (100 log lines).
 * Without token: builds a pre-filled GitHub issue URL (short report) and
 * returns the full log block separately for manual copy-paste into the issue.
 *
 * Referenced by: REQ-041
 */
import { readFileSync, existsSync } from "fs";
import path from "path";

const GITHUB_REPO = "popoboxxo/sharkord-vid-with-friends";
const GITHUB_API = "https://api.github.com";
const LOG_LINES_FULL = 100;
const LOG_LINES_SHORT = 20;
// GitHub URL limit is ~8192 chars; keep pre-filled body well under that
const PREFILLED_BODY_MAX = 1800;

type PluginContextLike = {
  commands: {
    register: <TArgs = void>(command: {
      name: string;
      description?: string;
      args?: { name: string; description?: string; type: string; required?: boolean }[];
      execute: (invoker: { userId: number; currentVoiceChannelId?: number }, args: TArgs) => Promise<unknown>;
    }) => void;
  };
  log: (...args: unknown[]) => void;
  error: (...args: unknown[]) => void;
  settings?: {
    get?: <T = unknown>(key: string) => T | undefined;
  };
};

/** Replace user IDs, IPs, and long CDN URLs with placeholders. */
const anonymizeLogLine = (line: string): string => {
  let result = line.replace(/\b(user\s+|userId[":]\s*)(\d+)/gi, "$1[USER]");
  result = result.replace(/https?:\/\/([^/\s]{1,60})[^\s"']*/g, (_, domain) => `https://${domain}/[...]`);
  result = result.replace(/\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/g, "[IP]");
  return result;
};

const readLogTail = (filename: string, lineCount: number): string => {
  const homeDir = process.env.HOME ?? process.env.USERPROFILE ?? process.cwd();
  const logPath = path.join(homeDir, ".config", "sharkord", "logs", filename);
  if (!existsSync(logPath)) return `(${filename} not found)`;
  try {
    const lines = readFileSync(logPath, "utf-8").split("\n").filter((l) => l.trim().length > 0);
    return lines.slice(-lineCount).map(anonymizeLogLine).join("\n");
  } catch {
    return `(could not read ${filename})`;
  }
};

const readPluginVersion = (): string => {
  try {
    const pkg = JSON.parse(readFileSync(path.join(process.cwd(), "package.json"), "utf-8")) as { version?: string };
    return pkg.version ?? "unknown";
  } catch {
    return "unknown";
  }
};

const buildSettingsBlock = (settings: Record<string, unknown>): string =>
  Object.entries(settings)
    .map(([k, v]) => `  ${k}: ${String(v)}`)
    .join("\n") || "  (not available)";

/** Full issue body — used when a token is available. */
const buildFullBody = (
  description: string,
  settingsBlock: string,
  version: string,
  recentLogs: string,
  errorLogs: string
): string => `## Bug Description

${description}

## Environment

- **Plugin Version:** \`${version}\`
- **Platform:** ${process.platform}
- **Reported at:** ${new Date().toISOString()}

## Active Settings

\`\`\`
${settingsBlock}
\`\`\`

## Recent Log (last ${LOG_LINES_FULL} lines, anonymized)

\`\`\`
${recentLogs}
\`\`\`

## Error Log (last 30 lines, anonymized)

\`\`\`
${errorLogs}
\`\`\`

---
*Auto-generated by \`/vid-bugreport\`. User IDs and IPs have been anonymized.*`;

/** Short issue body for the pre-filled URL — only errors + settings. */
const buildShortBody = (
  description: string,
  settingsBlock: string,
  version: string,
  errorLogs: string
): string => `## Bug Description

${description}

## Environment

- **Plugin Version:** \`${version}\`
- **Platform:** ${process.platform}

## Active Settings

\`\`\`
${settingsBlock}
\`\`\`

## Recent Errors (last ${LOG_LINES_SHORT} lines, anonymized)

\`\`\`
${errorLogs}
\`\`\`

---
*Paste the full log from the chat message below into this issue.*`;

/** Build a GitHub new-issue URL with pre-filled title + body (max ~2000 chars total). */
const buildPrefilledUrl = (title: string, body: string): string => {
  const truncated = body.length > PREFILLED_BODY_MAX
    ? body.substring(0, PREFILLED_BODY_MAX) + "\n\n*(truncated — paste full log from chat)*"
    : body;
  const params = new URLSearchParams({ title, body: truncated });
  return `https://github.com/${GITHUB_REPO}/issues/new?${params.toString()}`;
};

/** Post a GitHub issue via REST API. Returns the issue URL. */
const postGitHubIssue = async (token: string, title: string, body: string): Promise<string> => {
  const response = await fetch(`${GITHUB_API}/repos/${GITHUB_REPO}/issues`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    body: JSON.stringify({ title, body, labels: ["bug", "user-report"] }),
  });

  if (!response.ok) {
    const errText = await response.text().catch(() => "(no body)");
    throw new Error(`GitHub API error ${response.status}: ${errText.substring(0, 200)}`);
  }

  const data = await response.json() as { html_url?: string };
  return data.html_url ?? "(no URL in response)";
};

export const registerBugReportCommand = (ctx: PluginContextLike): void => {
  ctx.commands.register<{ description: string }>({
    name: "vid-bugreport",
    description: "Report a bug — creates an anonymized GitHub issue",
    args: [
      {
        name: "description",
        description: "Describe the problem you encountered",
        type: "string",
        required: true,
      },
    ],
    execute: async (_invoker, args) => {
      const description = args.description?.trim();
      if (!description) {
        throw new Error("Please describe the problem: /vid-bugreport <description>");
      }

      const settingKeys = ["videoBitrate", "audioBitrate", "defaultVolume", "syncMode", "fullDownloadMode", "debugMode"];
      const settings: Record<string, unknown> = {};
      for (const key of settingKeys) {
        settings[key] = ctx.settings?.get?.(key) ?? "(not set)";
      }

      const version = readPluginVersion();
      const settingsBlock = buildSettingsBlock(settings);
      const recentLogs = readLogTail("combined.log", LOG_LINES_FULL);
      const errorLogs = readLogTail("error.log", LOG_LINES_SHORT);
      const issueTitle = `[User Report] ${description.substring(0, 80)}`;

      const token = ctx.settings?.get?.<string>("githubToken");

      if (token?.trim()) {
        // With token: post full issue directly
        ctx.log("[bugreport] Posting GitHub issue...");
        try {
          const fullBody = buildFullBody(description, settingsBlock, version, recentLogs, errorLogs);
          const issueUrl = await postGitHubIssue(token.trim(), issueTitle, fullBody);
          ctx.log(`[bugreport] Issue created: ${issueUrl}`);
          return { response: `Bug report submitted: ${issueUrl}` };
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          ctx.error("[bugreport] Failed to post GitHub issue:", msg);
          throw new Error(`Could not create GitHub issue: ${msg}`);
        }
      }

      // Without token: pre-filled issue URL (short body) + full log in chat (REQ-046: plaintext)
      const shortBody = buildShortBody(description, settingsBlock, version, errorLogs);
      const prefilledUrl = buildPrefilledUrl(issueTitle, shortBody);

      return {
        response: [
          `Open this link to create the issue (form is pre-filled):`,
          prefilledUrl,
          ``,
          `Then paste the full log below into the issue:`,
          ``,
          recentLogs,
        ].join("\n"),
      };
    },
  });
};

